#ifndef _APP_ERROR_H_
#define _APP_ERROR_H_

typedef enum
{
    APP_OK = 0,

    NET_ERR_WIFI_CONNECT = 0x1000,
    NET_ERR_DNS_FAIL,
    NET_ERR_SOCKET_TIMEOUT,
    NET_ERR_MODULE,

    HTTP_ERR_STATUS_CODE = 0x2000,
    HTTP_ERR_HEADER_PARSE,
    HTTP_ERR_CONTENT_LENGTH,
    HTTP_ERR_RANGE_NOT_SUPPORT,
    HTTP_ERR_CHUNKED_NOT_SUPPORT,

    FLASH_ERR_ERASE = 0x3000,
    FLASH_ERR_WRITE,
    FLASH_ERR_READ,

    OTA_ERR_MD5_MISMATCH = 0x4000,
    OTA_ERR_SIZE_MISMATCH,
    OTA_ERR_VERSION_INVALID,
    OTA_ERR_RESUME_INVALID,
    OTA_ERR_PROGRESS_SAVE,

    IAP_ERR_METADATA_INVALID = 0x5000,
    IAP_ERR_BOOT_FLAG_WRITE,
    IAP_ERR_ROLLBACK
} AppError_t;

#endif
